"""Application configuration for WBCP Web."""
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATASETS_DIR = os.path.join(BASE_DIR, "datasets")
UPLOADS_DIR = os.path.join(BASE_DIR, "uploads")
MAX_UPLOAD_SIZE_MB = 50
ALLOWED_EXTENSIONS = {".csv"}

# Built-in dataset registry with pre-configured column mappings
BUILTIN_DATASETS = {
    "US_Health_ARTHRITIS": {
        "file": "US_Health_ARTHRITIS.csv",
        "target": "ARTHRITIS_AdjPrev",
        "features": ["ACCESS2_AdjPrev", "CHECKUP_AdjPrev", "DENTAL_AdjPrev", "BINGE_AdjPrev", "CSMOKING_AdjPrev", "LPA_AdjPrev", "SLEEP_AdjPrev", "EMOTIONSPT_AdjPrev"],
        "coords": ["lon", "lat"],
        "coord_type": "geodetic",
        "region": "StateAbbr",
        "metadata_sheet": "US_Health_ARTHRITIS",
        "description": "US Health - Arthritis prevalence among adults (2022)",
    },
    "US_Health_BPHIGH": {
        "file": "US_Health_BPHIGH.csv",
        "target": "BPHIGH_AdjPrev",
        "features": ["ACCESS2_AdjPrev", "CHECKUP_AdjPrev", "DENTAL_AdjPrev", "BINGE_AdjPrev", "CSMOKING_AdjPrev", "LPA_AdjPrev", "SLEEP_AdjPrev", "EMOTIONSPT_AdjPrev"],
        "coords": ["lon", "lat"],
        "coord_type": "geodetic",
        "region": "StateAbbr",
        "metadata_sheet": "US_Health_BPHIGH",
        "description": "US Health - High blood pressure prevalence (2022)",
    },
    "US_Health_CANCER": {
        "file": "US_Health_CANCER.csv",
        "target": "CANCER_AdjPrev",
        "features": ["ACCESS2_AdjPrev", "CHECKUP_AdjPrev", "DENTAL_AdjPrev", "BINGE_AdjPrev", "CSMOKING_AdjPrev", "LPA_AdjPrev", "SLEEP_AdjPrev", "EMOTIONSPT_AdjPrev"],
        "coords": ["lon", "lat"],
        "coord_type": "geodetic",
        "region": "StateAbbr",
        "metadata_sheet": "US_Health_CANCER",
        "description": "US Health - Cancer prevalence (2022)",
    },
    "US_Health_CASTHMA": {
        "file": "US_Health_CASTHMA.csv",
        "target": "CASTHMA_AdjPrev",
        "features": ["ACCESS2_AdjPrev", "CHECKUP_AdjPrev", "DENTAL_AdjPrev", "BINGE_AdjPrev", "CSMOKING_AdjPrev", "LPA_AdjPrev", "SLEEP_AdjPrev", "EMOTIONSPT_AdjPrev"],
        "coords": ["lon", "lat"],
        "coord_type": "geodetic",
        "region": "StateAbbr",
        "metadata_sheet": "US_Health_CASTHMA",
        "description": "US Health - Current asthma prevalence (2022)",
    },
    "US_Health_DEPRESSION": {
        "file": "US_Health_DEPRESSION.csv",
        "target": "DEPRESSION_AdjPrev",
        "features": ["ACCESS2_AdjPrev", "CHECKUP_AdjPrev", "DENTAL_AdjPrev", "BINGE_AdjPrev", "CSMOKING_AdjPrev", "LPA_AdjPrev", "SLEEP_AdjPrev", "EMOTIONSPT_AdjPrev"],
        "coords": ["lon", "lat"],
        "coord_type": "geodetic",
        "region": "StateAbbr",
        "metadata_sheet": "US_Health_DEPRESSION",
        "description": "US Health - Depression prevalence (2022)",
    },
    "US_Health_DIABETES": {
        "file": "US_Health_DIABETES.csv",
        "target": "DIABETES_AdjPrev",
        "features": ["ACCESS2_AdjPrev", "CHECKUP_AdjPrev", "DENTAL_AdjPrev", "BINGE_AdjPrev", "CSMOKING_AdjPrev", "LPA_AdjPrev", "SLEEP_AdjPrev", "EMOTIONSPT_AdjPrev"],
        "coords": ["lon", "lat"],
        "coord_type": "geodetic",
        "region": "StateAbbr",
        "metadata_sheet": "US_Health_DIABETES",
        "description": "US Health - Diabetes prevalence (2022)",
    },
    "US_Health_OBESITY": {
        "file": "US_Health_OBESITY.csv",
        "target": "OBESITY_AdjPrev",
        "features": ["ACCESS2_AdjPrev", "CHECKUP_AdjPrev", "DENTAL_AdjPrev", "BINGE_AdjPrev", "CSMOKING_AdjPrev", "LPA_AdjPrev", "SLEEP_AdjPrev", "EMOTIONSPT_AdjPrev"],
        "coords": ["lon", "lat"],
        "coord_type": "geodetic",
        "region": "StateAbbr",
        "metadata_sheet": "US_Health_OBESITY",
        "description": "US Health - Obesity prevalence (2022)",
    },
    "US_Health_STROKE": {
        "file": "US_Health_STROKE.csv",
        "target": "STROKE_AdjPrev",
        "features": ["ACCESS2_AdjPrev", "CHECKUP_AdjPrev", "DENTAL_AdjPrev", "BINGE_AdjPrev", "CSMOKING_AdjPrev", "LPA_AdjPrev", "SLEEP_AdjPrev", "EMOTIONSPT_AdjPrev"],
        "coords": ["lon", "lat"],
        "coord_type": "geodetic",
        "region": "StateAbbr",
        "metadata_sheet": "US_Health_STROKE",
        "description": "US Health - Stroke prevalence (2022)",
    },
    "US_Politics_Voting": {
        "file": "US_Politics_Voting.csv",
        "target": "new_pct_dem",
        "features": ["sex_ratio", "pct_black", "pct_hisp", "pct_bach", "median_income", "pct_65_over", "pct_age_18_29", "gini", "pct_manuf", "ln_pop_den", "pct_3rd_party", "turn_out", "pct_fb", "pct_uninsured"],
        "coords": ["proj_x", "proj_y"],
        "coord_type": "projected",
        "epsg": 5070,  # NAD83 / Conus Albers Equal Area
        "region": "state",
        "metadata_sheet": "US_Politics_Voting",
        "description": "US Politics - Democratic voting percentage",
    },
    "Seattle_Housing": {
        "file": "seattle_sample_3k.csv",
        "target": "log_price",
        "features": ["bathrooms", "sqft_living", "sqft_lot", "grade", "condition", "waterfront", "view", "age"],
        "coords": ["UTM_X", "UTM_Y"],
        "coord_type": "projected",
        "epsg": 32610,  # UTM Zone 10N
        "region": None,
        "metadata_sheet": None,
        "description": "Seattle Housing - Log price prediction (3k samples)",
    },
}

# CP Method registry
METHOD_REGISTRY = {
    "standard_cp": {
        "label": "Standard CP",
        "group": "Standard",
        "weight_fn": "uniform",
        "bayesian": False,
        "needs_coords": False,
        "params": ["alpha"],
    },
    "bqcp": {
        "label": "BQ-CP (Bayesian Quadrature)",
        "group": "Standard",
        "weight_fn": "uniform",
        "bayesian": True,
        "needs_coords": False,
        "params": ["alpha", "beta", "num_mc"],
    },
    "geocp": {
        "label": "GeoCP",
        "group": "Spatial",
        "weight_fn": "spatial_kernel",
        "bayesian": False,
        "needs_coords": True,
        "params": ["alpha", "bandwidth"],
    },
    "geobcp": {
        "label": "GeoBCP",
        "group": "Spatial",
        "weight_fn": "spatial_kernel",
        "bayesian": True,
        "needs_coords": True,
        "params": ["alpha", "bandwidth", "beta", "num_mc"],
    },
    "adaptive_geocp": {
        "label": "Adaptive GeoCP",
        "group": "Spatial",
        "weight_fn": "adaptive_spatial",
        "bayesian": False,
        "needs_coords": True,
        "params": ["alpha", "base_bandwidth", "k_adaptive"],
    },
    "adaptive_geobcp": {
        "label": "Adaptive GeoBCP",
        "group": "Spatial",
        "weight_fn": "adaptive_spatial",
        "bayesian": True,
        "needs_coords": True,
        "params": ["alpha", "base_bandwidth", "k_adaptive", "beta", "num_mc"],
    },
    "localized_cp": {
        "label": "Localized CP (k-NN)",
        "group": "Feature",
        "weight_fn": "knn",
        "bayesian": False,
        "needs_coords": False,
        "params": ["alpha", "k"],
    },
    "geosimcp_l2": {
        "label": "GeoSIMCP (L2)",
        "group": "Feature",
        "weight_fn": "spatial_feature_l2",
        "bayesian": False,
        "needs_coords": True,
        "params": ["alpha", "bandwidth", "lambda_weight"],
    },
    "geosimcp_zhao": {
        "label": "GeoSIMCP (Zhao)",
        "group": "Feature",
        "weight_fn": "spatial_feature_minmax",
        "bayesian": False,
        "needs_coords": True,
        "params": ["alpha", "bandwidth", "lambda_weight"],
    },
    "gwqr": {
        "label": "GWQR",
        "group": "Alternative",
        "class": "GWQRConformalPredictor",
        "bayesian": False,
        "needs_coords": True,
        "async": True,
        "params": ["alpha", "k", "n_jobs"],
    },
    "lscp": {
        "label": "LSCP",
        "group": "Alternative",
        "class": "LSCPConformalPredictor",
        "bayesian": False,
        "needs_coords": True,
        "async": True,
        "params": ["alpha", "k", "n_jobs"],
    },
}

# Default parameter values
DEFAULT_PARAMS = {
    "alpha": 0.1,
    "beta": 0.9,
    "num_mc": 1000,
    "bandwidth": 0.15,
    "base_bandwidth": 0.15,
    "k": 20,
    "k_adaptive": 200,
    "lambda_weight": 0.5,
    "n_jobs": 4,
}
